Changed gh-pages workflow to other version

diff --git a/.github/workflows/gh-pages.yml b/.github/workflows/gh-pages.yml
--- a/.github/workflows/gh-pages.yml
+++ b/.github/workflows/gh-pages.yml
@@ -1,32 +1,33 @@
-name: github pages
-
-on:
-  push:
-    branches:
-      - main  # Set a branch to deploy
-  pull_request:
-
+name: Build and Deploy
+on: [push]
 jobs:
-  deploy:
-    runs-on: ubuntu-20.04
+  build-and-deploy:
+    runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@v2
+      - name: Checkout 🛎️
+        uses: actions/checkout@v2.3.1
         with:
-          submodules: true  # Fetch Hugo themes (true OR recursive)
-          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
+          persist-credentials: false
 
-      - name: Setup Hugo
-        uses: peaceiris/actions-hugo@v2
+      - name: Update Theme 🔧 
+        run: git submodule update --init --recursive
+
+      - name: Setup Hugo 🔧
+        run: | 
+          sudo apt update
+          wget ${{ secrets.HUGO_RELEASE }} -O hugo.deb
+          sudo dpkg -i hugo.deb
+          sudo apt install -f
+      - name: Testing Hugo 🔧
+        run: 'command -v hugo >/dev/null 2>&1 || { echo >&2 "Where is Hugo? Aborting."; exit 1; }'
+
+      - name: Build blog 🔧
+        run: hugo -D --minify
+
+      - name: Deploy 🚀
+        uses: JamesIves/github-pages-deploy-action@3.7.1
         with:
-          hugo-version: 'latest'
-          # extended: true
-
-      - name: Build
-        run: hugo --minify
-
-      - name: Deploy
-        uses: peaceiris/actions-gh-pages@v3
-        if: github.ref == 'refs/heads/main'
-        with:
-          github_token: ${{ secrets.GITHUB_TOKEN }}
-          publish_dir: ./public
+          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
+          BRANCH: gh-pages
+          FOLDER: public
+          CLEAN: true 
